encoding: utf-8

# SEO相关信息
title: Congbo Song | The University of Manchester
description: Congbo Song, NCAS, the University of Manchester
keywords: Congbo Song, CongboSong, SongCongbo, Song Congbo, 宋从波, Congbo, Birmingham, Manchester, University of Birmingham, University of Manchester, NCAS, Air pollution, Air quality, Clean air, Machine learning
author: Congbo Song
footerText: '© CC BY-NC-SA 4.0'

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'blog.sh']

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
domainUrl: 'https://congbo.site'
baseurl: ''
sourcecode:
# 吐个槽地址，会在chat页面中重定向到该地址
#tucaoUrl:

# 菜单
# 必填字段 title: '文本' url: '链接'
# 可选字段 target: '_blank' 新页面打开

menu:
  - title: About
    url: /
  - title: Blog
    url: /pages/post.html
  - title: Tags
    url: /pages/tags.html
  - title: Search
    url: /pages/search.html
  - title: Projects
    url: /pages/projects.html
  - title: Papers
    url: /pages/papers.html
  - title: CV
    url: /pages/cv.html
  - title: Contact
    url: /pages/contact.html

# 点击页面文字冒出特效,不需要请设置为false
extClickEffect: false

# Google Adsense,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extAdsense: false

# 数学公式支持，比较影响加载速度,不需要请设置为false
extMath: false

valine:
  serverURLs: https://xrrro58n.api.lncldglobal.com
  enable: true    #是否开启valine评论
  id: xrRRo58nrl4YV9rUeNOePKr9-MdYXbMMI
  key: 90tIVi6XRevzSAzvojiOKwlR
  js: /static/js/Valine.min.js
  placeholder: Get in touch here
  avatar: mp
  visitor: true
  master: b8d6b6976b3ec45bccc6aa9816c40db7
  requiredFields: ['mail']
  pageSize: 10
  mathJax: false
  enableQQ: true


links:
  - title: David Topping
    url: https://davidtoppingsci.com
    desc: A Wandering Scientist in the University of Manchester, Fellow of the Alan Turing Data Science Institute
    header: https://davidtoppingsci.files.wordpress.com/2014/10/mer2d2.jpg?w=788&h=788
  - title: Zhonghua Zheng
    url: https://zhonghuazheng.com/
    desc: Lecturer in Data Science & Environmental Analytics, the University of Manchester
    header: https://zhonghuazheng.com/src/selfie.jpg
  - title: Manchester Environmental Data Analytics Lab (MEDAL)
    url: https://m-edal.github.io
    desc: nvironmental Data Analytics Lab in University of Manchester
    header: https://m-edal.github.io/src/medal.jpg
  - title: Clean Air Research Group of Zongbo Shi
    url: https://clean-air-research.org.uk
    desc: Clean Air Research Group website hosted by Professor Zongbo Shi at the University of Birmingham.
    header: https://clean-air-research.org.uk/wp-content/uploads/Clean-Air-Research-Logo.png
  - title: William (Bill) Bloss
    url: https://www.williambloss.com
    desc: Professor of Atmospheric Science in University of Birmingham.
    header: https://static.wixstatic.com/media/4cf9c9_0dd47aadf7064046a1a343aedb6a1e2b~mv2.jpg/v1/crop/x_0,y_58,w_1194,h_1205/fill/w_940,h_948,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/4cf9c9_0dd47aadf7064046a1a343aedb6a1e2b~mv2.jpg
  - title: TMaize的个人博客
    url: https://blog.tmaize.net
    desc: TMaize的个人博客
    header: https://blog.tmaize.net/static/img/logo.jpg
  - title: Dr Tuan Vu
    url: https://tuanvvu.github.io
    desc: Senior air quality scientist at Environmental Research Group, Imperial College London
    header: https://tuanvvu.github.io/assets/images/bio-photo.jpg
  - title: Yuqing Dai
    url: https://yuqingdai.xyz
    desc: Air quality modeller, street cannoy studies
    header: https://yuqingdai.xyz/pics/common/bio.jpg
  - title: Susan Athey
    url: https://gsb-faculty.stanford.edu/susan-athey/
    desc: The Economics of Technology Professor, Stanford Graduate School of Business
    header: https://gsb-faculty.stanford.edu/susan-athey/files/2022/04/photo-faculty-athey-susan-1.jpg
  - title: Song Xi Chen (陈松蹊) Group
    url: https://www.songxichen.com
    desc: Developing statistical methodologies and applications in Air Quality Assessment
    header: https://www.songxichen.com/Uploads/user_photo/thumb_1490748596.jpg
